name: Manual Apply or Destroy

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose whether to apply or destroy"
        required: true
        default: apply
        type: choice
        options:
          - apply
          - destroy

env:
  TF_VERSION: 1.6.6

jobs:
  deploy:
    name: Apply or Destroy Infrastructure
    runs-on: ubuntu-latest
    environment:
      name: production  # Enables manual approval before this job runs

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: terraform init

      - name: Terraform Action
        run: |
          if [[ "${{ github.event.inputs.action }}" == "apply" ]]; then
            terraform apply -auto-approve
          else
            terraform destroy -auto-approve
          fi
