name: Terraform GitOps

on:
  push:
    branches:
      - main
  pull_request:

env:
  TF_VERSION: 1.6.6
  AWS_REGION: us-east-1  # ✅ Define region as a global env var

jobs:
  terraform-ci:
    name: Init | Validate | Plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}  # ✅ Use from env

      - run: terraform init

      - run: terraform validate

      - run: terraform plan

  terraform-cd:
    name: Manual Approval & Apply
    needs: terraform-ci
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: production
      # ✅ Enforces manual approval via GitHub Environments (Settings > Environments > production)

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: terraform init

      - run: terraform apply -auto-approve
